services:
  database:
    build: ./database
    environment:
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PWD=secret
    depends_on:
      - database

      
    