services:
  database:
    build: ./database
    environment:
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
  
  backend:
    build: ./backend
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PWD=secret
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - MESSAGE="Hallo Welt"
      - BACKEND_ENDPOINT="http://backend:3000/"
    depends_on:
      - backend

      
    